url: twinbasic.github.io
title: twinBASIC Documentation
baseurl: /

# note: redcarpet is not supported on github pages
markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true

#remote_theme: pages-themes/slate@v0.2.0
remote_theme: just-the-docs/just-the-docs@v0.10.1

plugins:
- jekyll-remote-theme    

#defaults:
#  - scope:
#      path: ""
#    values:
#      layout: default

#collections:
#  intro:
#    output: true
#  features:
#    output: true
#  samples:
#    output: true
      
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
