title: twinBASIC Documentation
logo: favicon.png
logo_with_title: true
baseurl: /

# note: redcarpet is not supported on github pages
markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  input: GFM

remote_theme: just-the-docs/just-the-docs@v0.10.1

highlighter: rouge

defaults:
  - scope:
      path: "*/Images"
    values:
      image: true

# GitHub-style admonitions are supported, but we may wish to add custom
# callouts below.
callouts:
  #tip:
  #  title: ðŸ’¡ Tip
  #  color: green

#defaults:
#  - scope:
#      path: ""
#    values:
#      layout: default

#collections:
#  intro:
#    output: true
#  features:
#    output: true
#  samples:
#    output: true
      
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
